# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 16:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Phone number must be in format 421915123456', regex='^42(0|1){1}\\d{3}\\d{3}\\d{3}$')])),
                ('is_blocked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Blocked number',
                'verbose_name_plural': 'Blocked numbers',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Phone number must be in format 421915123456', regex='^42(0|1){1}\\d{3}\\d{3}\\d{3}$')])),
                ('call_date', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Record',
                'verbose_name_plural': 'Records',
            },
        ),
    ]
