# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='upload_to',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
