# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_record_upload_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='call_type',
            field=models.CharField(blank=True, choices=[('1', 'Incoming'), ('2', 'Outcoming')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='upload_to',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
