# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_record_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='is_blocked',
            field=models.BooleanField(default=True),
        ),
    ]
