# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_auto_20171117_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='is_recorded',
            field=models.NullBooleanField(default=True),
        ),
    ]
