# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_blacklist_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='is_recorded',
            field=models.NullBooleanField(default=True),
        ),
    ]
