version: '2'
services:
  web:
    build: .
    container_name: dg01
    depends_on:
      - db
    volumes:
      - ./src:/src
    ports:
      - "8000:8000"

  db:
    image: postgres:latest
    container_name: ps01
